### ISSUE TITLE
about  save_musdb_XL_train_wave.py of Musdb-XL-train

### ISSUE THREAD

**Issue by will46616** [jeonchangbin49/De-limiter#1]
Hi, I've followed the instruction of Musdb-XL-train website, but I got some mismatches between ratio from npy file and musdb_hq dataset.
File "/home3/will/save_musdb_XL_train_wave.py", line 72, in main
    output = mixture * ratio
ValueError: operands could not be broadcast together with shapes (2,10053632) (2,10061547)

**Comment by jeonchangbin49** [comment]
Hi, it seems that there occurs a size mismatch problem between the audio and .npy files. Could you let me know which file caused the problem? Simple print("fixed_song") after line 58 will show you that.

**Comment by will46616** [comment]
fixed_song ['The Districts - Vermont', '-5.16', '1.0']
(2, 10053632) (2, 10061547)
  0%|                                                   | 0/100 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "/home3/will/save_musdb_XL_train_wave.py", line 147, in <module>
    main()
  File "/home3/will/save_musdb_XL_train_wave.py", line 73, in main
    output = mixture * ratio
ValueError: operands could not be broadcast together with shapes (2,10053632) (2,10061547) 

Thank you for replying, the file is 'The Districts - Vermont'.

**Comment by jeonchangbin49** [comment]
Hmm, it's weird. I think it's very unlikely that your 'The Districts - Vermont' and my 'The Districts - Vermont' have different lengths because it seems that there is only one version of musdb18-hq available in https://zenodo.org/records/3338373. I'll get back to you after I check the audio length maybe this weekend or next week. Let me know if you have more info regarding the problem.

**Comment by will46616** [comment]
Thanks for your reply, I downloaded my MUSDB18-HQ dataset from the same URL. I will inform you if there is any other information.

**Comment by jeonchangbin49** [comment]
Sorry for keeping you waiting so long. I re-downloaded and checked the length of "The Districts - Vermont" file and the musdb-XL-train version of it and their shapes were all the same. Now I'm downloading .npy files of musdb-XL-train to check if there is some problem in tar.xz file. Didn't you have any problem while downloading and unzipping the tar.xz file?

**Comment by will46616** [comment]
Downloading and unzipping went smoothly without any problems. The size of the unzipped musdb-XL-train folder is about 215GB.
